MASK_CONFIGS = {
    "belarus": {
        "name": "Флаг беларуси",
        "file": "masks/bel.png",
        "left": 411,
        "right": 435,
        "top": 356,
        "bottom": 152,
        "center": 411,
        "scale_w": 1,
        "scale_h": 2,
        "start_point_x": 0,
        "start_point_y": 0,
        "rotate": False,
        "place_on_point": False,
        "native_size": True,
        "animated": False
    },
    "dog-nose": {
        "name": "Нос собаки",
        "file": "masks/dog-nose.png",
        "left": 49,
        "right": 279,
        "top": 195,
        "bottom": 1,
        "center": 5,
        "scale_w": 2,
        "scale_h": 1,
        "start_point_x": 0,
        "start_point_y": 0,
        "rotate": False,
        "place_on_point": False,
        "native_size": True,
        "animated": False
    },
    "crown": {
        "name": "Корона",
        "file": "masks/gold-crown.png",
        "left": 69,
        "right": 71,
        "top": 109,
        "bottom": 1,
        "center": 10,
        "scale_w": 2,
        "scale_h": 1,
        "start_point_x": 256,
        "start_point_y": 40,
        "rotate": False,
        "place_on_point": True,
        "native_size": True,
        "animated": False
    },
    "glasses": {
        "name": "Очки",
        "file": "masks/glasses.png",
        "left": 127,
        "right": 356,
        "top": 9,
        "bottom": 197,
        "center": 168,
        "scale_w": 1,
        "scale_h": 1,
        "start_point_x": 0,
        "start_point_y": 0,
        "rotate": True,
        "place_on_point": False,
        "native_size": True,
        "animated": False
    },
    "dog-tonque": {
        "name": "Язык собаки",
        "file": "masks/dog-tongue.gif",
        "left": 127,
        "right": 356,
        "top": 9,
        "bottom": 197,
        "center": 168,
        "scale_w": 1,
        "scale_h": 1,
        "start_point_x": 0,
        "start_point_y": 0,
        "rotate": True,
        "place_on_point": False,
        "native_size": True,
        "animated": True
    },
}
